import logging
import os
import asyncio

from dotenv import load_dotenv
from livekit import agents
from livekit.agents import AgentServer, AgentSession, Agent
from livekit.plugins import google
from openai import OpenAI

load_dotenv(".env.local")
load_dotenv(".env", override=False)

logger = logging.getLogger(__name__)

REALTIME_MODEL = "gemini-3.1-flash-live-preview"
VOICE = "Zephyr"
NEBIUS_BASE_URL = os.getenv("NEBIUS_BASE_URL", "https://api.tokenfactory.nebius.com/v1")
NEBIUS_MODEL = os.getenv("NEBIUS_MODEL", "deepseek-ai/DeepSeek-V3-0324")
NEBIUS_PROMPT_ENABLED = os.getenv("NEBIUS_PROMPT_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
}

INSTRUCTIONS = """You are a helpful voice assistant powered by Gemini.
Be concise, friendly, and conversational."""


def _generate_nebius_prompt_hint() -> str | None:
    """Return a short style directive generated by Nebius, or None if unavailable."""
    nebius_api_key = os.getenv("NEBIUS_API_KEY")
    if not NEBIUS_PROMPT_ENABLED or not nebius_api_key:
        return None

    client = OpenAI(base_url=NEBIUS_BASE_URL, api_key=nebius_api_key)
    completion = client.chat.completions.create(
        model=NEBIUS_MODEL,
        temperature=0.2,
        max_tokens=120,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a prompt optimizer for a realtime voice assistant. "
                    "Return 2-3 short bullets that improve speaking style, clarity, and "
                    "conciseness. Keep output under 70 words."
                ),
            },
            {
                "role": "user",
                "content": (
                    "Base behavior: helpful, concise, friendly, conversational voice assistant. "
                    "Generate style guidance only."
                ),
            },
        ],
    )

    message = completion.choices[0].message.content
    if not message:
        return None

    return message.strip()


async def build_agent_instructions() -> str:
    """Build runtime instructions, optionally enriched by Nebius Token Factory."""
    try:
        nebius_hint = await asyncio.to_thread(_generate_nebius_prompt_hint)
    except Exception as exc:
        logger.warning("Nebius hint generation failed, continuing without it: %s", exc)
        nebius_hint = None

    if not nebius_hint:
        return INSTRUCTIONS

    logger.info("Nebius Token Factory prompt hint enabled")
    return (
        f"{INSTRUCTIONS}\n\n"
        "Additional speaking guidance generated by Nebius Token Factory:\n"
        f"{nebius_hint}"
    )


class VoiceAgent(Agent):
    def __init__(self, instructions: str) -> None:
        super().__init__(instructions=instructions)

server = AgentServer()

@server.rtc_session(agent_name="gemini-voice-agent")
async def entrypoint(ctx: agents.JobContext):
    instructions = await build_agent_instructions()

    session = AgentSession(
        llm=google.realtime.RealtimeModel(
            model=REALTIME_MODEL,
            voice=VOICE,
        )
    )

    await session.start(
        room=ctx.room,
        agent=VoiceAgent(instructions=instructions),
    )

if __name__ == "__main__":
    agents.cli.run_app(server)
