"""Gemini embedding helper for semantic product search.

The query embedding is generated by the application (not the database, not
Toolbox). It is passed to the `semantic_product_search` Toolbox tool, which runs
the MongoDB $vectorSearch. The embedding model + dimension MUST match what was
used to build the inventory embeddings (gemini-embedding-001, 3072 dims).
"""
from functools import lru_cache

from google import genai
from google.genai import types

from agent import config


@lru_cache(maxsize=1)
def _client() -> "genai.Client":
    # Uses GOOGLE_API_KEY (or Vertex AI ADC) from the environment.
    return genai.Client()


def generate_embeddings(query: str) -> list[float]:
    """Return the Gemini embedding vector for a free-text product query."""
    result = _client().models.embed_content(
        model=config.EMBEDDING_MODEL,
        contents=query,
        config=types.EmbedContentConfig(output_dimensionality=config.EMBEDDING_DIM),
    )
    return list(result.embeddings[0].values)
